@echo off
echo Starting Backend Server...
cd /d "e:\Ai Agents\Langchian"
echo Installing dependencies...
.\zen_ai\venv\Scripts\python.exe -m pip install -r .\zen_ai\requirements.txt
echo Starting server...
.\zen_ai\venv\Scripts\python.exe -m uvicorn zen_ai.backend.app:app --reload
